name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Es desplega quan fem un push a "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Passar Secret a Streamlit
        run: echo "FCOC_PLAYOFF_API_TOKEN=${{ secrets.FCOC_PLAYOFF_API_TOKEN }}" >> ~/.streamlit/secrets.toml

      - name: Executar Streamlit
        run: streamlit run streamlit_app.py
